[2025-04-04T04:09:30.332+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T04:09:30.357+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline.generate_visualizations manual__2025-04-04T04:08:57.954664+00:00 [queued]>
[2025-04-04T04:09:30.366+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline.generate_visualizations manual__2025-04-04T04:08:57.954664+00:00 [queued]>
[2025-04-04T04:09:30.366+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-04T04:09:30.380+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_visualizations> on 2025-04-04 04:08:57.954664+00:00
[2025-04-04T04:09:30.387+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=370) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-04T04:09:30.390+0000] {standard_task_runner.py:63} INFO - Started process 379 to run task
[2025-04-04T04:09:30.390+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline', 'generate_visualizations', 'manual__2025-04-04T04:08:57.954664+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmp_7r72yll']
[2025-04-04T04:09:30.394+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask generate_visualizations
[2025-04-04T04:09:30.456+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline.generate_visualizations manual__2025-04-04T04:08:57.954664+00:00 [running]> on host b9b2dee32edb
[2025-04-04T04:09:30.564+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline' AIRFLOW_CTX_TASK_ID='generate_visualizations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T04:08:57.954664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T04:08:57.954664+00:00'
[2025-04-04T04:09:30.566+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T04:09:32.679+0000] {tmdb_pipeline.py:670} ERROR - Error al leer datos de PostgreSQL: connection to server at "movie_postgres" (172.19.0.3), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-04T04:09:32.684+0000] {tmdb_pipeline.py:671} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 638, in generate_visualizations
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.3), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-04T04:09:34.238+0000] {tmdb_pipeline.py:744} INFO - Visualizaciones guardadas en /opt/***/data/movie_analytics/visualizations_20250404_040932
[2025-04-04T04:09:34.266+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/movie_analytics/visualizations_20250404_040932
[2025-04-04T04:09:34.267+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T04:09:34.292+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline, task_id=generate_visualizations, execution_date=20250404T040857, start_date=20250404T040930, end_date=20250404T040934
[2025-04-04T04:09:34.369+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-04T04:09:34.405+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-04T04:09:34.406+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
