[2025-04-10T13:29:53.473+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-10T13:29:53.503+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-10T13:29:53.513+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-10T13:29:53.514+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-04-10T13:29:53.529+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_kafka_data> on 2025-04-10 00:00:00+00:00
[2025-04-10T13:29:53.536+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7748) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-10T13:29:53.537+0000] {standard_task_runner.py:63} INFO - Started process 7752 to run task
[2025-04-10T13:29:53.537+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_v2', 'process_kafka_data', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '1023', '--raw', '--subdir', 'DAGS_FOLDER/dag_tmdb.py', '--cfg-path', '/tmp/tmpbbs1tn0h']
[2025-04-10T13:29:53.541+0000] {standard_task_runner.py:91} INFO - Job 1023: Subtask process_kafka_data
[2025-04-10T13:29:53.596+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-10T00:00:00+00:00 [running]> on host a24902f77b45
[2025-04-10T13:29:53.703+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_v2' AIRFLOW_CTX_TASK_ID='process_kafka_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-10T13:29:53.704+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-10T13:29:53.846+0000] {dag_tmdb.py:283} INFO - Iniciando proceso de consumo de datos de Kafka
[2025-04-10T13:29:53.848+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T13:29:53.863+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <checking_api_versions_recv> [IPv4 ('172.19.0.6', 9093)]>: Broker version identified as 2.6
[2025-04-10T13:29:53.864+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T13:29:53.865+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('tmdb_data',)
[2025-04-10T13:29:53.866+0000] {dag_tmdb.py:295} INFO - Consumidor conectado a Kafka, esperando mensajes en 'tmdb_data'...
[2025-04-10T13:29:53.866+0000] {dag_tmdb.py:339} INFO - Intento 1/3 de obtener mensajes
[2025-04-10T13:29:53.876+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T13:29:53.877+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T13:29:53.877+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:29:53.983+0000] {cluster.py:393} INFO - Group coordinator for ***_consumer_group_v2 is ('coordinator-1001', 'kafka', 9093, None)
[2025-04-10T13:29:53.984+0000] {base.py:729} INFO - Discovered coordinator coordinator-1001 for group ***_consumer_group_v2
[2025-04-10T13:29:53.984+0000] {base.py:780} INFO - Starting new heartbeat thread
[2025-04-10T13:29:53.985+0000] {consumer.py:361} INFO - Revoking previously assigned partitions () for group ***_consumer_group_v2
[2025-04-10T13:29:53.987+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T13:29:53.988+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T13:29:54.090+0000] {base.py:489} INFO - (Re-)joining group ***_consumer_group_v2
[2025-04-10T13:29:54.114+0000] {base.py:552} INFO - Elected group leader -- performing partition assignments using range
[2025-04-10T13:29:54.129+0000] {base.py:380} INFO - Successfully joined group ***_consumer_group_v2 with generation 17
[2025-04-10T13:29:54.131+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('tmdb_data', 0)]
[2025-04-10T13:29:54.132+0000] {consumer.py:252} INFO - Setting newly assigned partitions (('tmdb_data', 0),) for group ***_consumer_group_v2
[2025-04-10T13:29:58.868+0000] {dag_tmdb.py:352} INFO - No se recibieron suficientes mensajes, esperando... (0 hasta ahora)
[2025-04-10T13:30:00.871+0000] {dag_tmdb.py:339} INFO - Intento 2/3 de obtener mensajes
[2025-04-10T13:30:05.877+0000] {dag_tmdb.py:352} INFO - No se recibieron suficientes mensajes, esperando... (0 hasta ahora)
[2025-04-10T13:30:07.879+0000] {dag_tmdb.py:339} INFO - Intento 3/3 de obtener mensajes
[2025-04-10T13:30:12.882+0000] {dag_tmdb.py:352} INFO - No se recibieron suficientes mensajes, esperando... (0 hasta ahora)
[2025-04-10T13:36:58.228+0000] {base.py:1051} WARNING - Heartbeat session expired, marking coordinator dead
[2025-04-10T13:36:58.373+0000] {base.py:751} WARNING - Marking the coordinator dead (node coordinator-1001) for group ***_consumer_group_v2: Heartbeat session expired.
[2025-04-10T13:36:58.237+0000] {dag_tmdb.py:357} WARNING - No se recibieron mensajes de Kafka. Usando datos de ejemplo.
[2025-04-10T13:36:58.418+0000] {dag_tmdb.py:378} INFO - Procesando 1 mensajes con Pandas
[2025-04-10T13:36:58.811+0000] {cluster.py:393} INFO - Group coordinator for ***_consumer_group_v2 is ('coordinator-1001', 'kafka', 9093, None)
[2025-04-10T13:36:58.843+0000] {base.py:729} INFO - Discovered coordinator coordinator-1001 for group ***_consumer_group_v2
[2025-04-10T13:36:58.949+0000] {dag_tmdb.py:427} INFO - Datos procesados guardados en /opt/***/data/movie_analytics/processed_movies_v2.csv
[2025-04-10T13:36:59.076+0000] {consumer.py:565} ERROR - Offset commit failed: This is likely to cause duplicate message delivery
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/coordinator/consumer.py", line 554, in _maybe_auto_commit_offsets_sync
    self.commit_offsets_sync(self._subscription.all_consumed_offsets(), timeout_ms=timeout_ms)
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/coordinator/consumer.py", line 547, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
    ^^^^^^^^^^^^^^^^^^^^^^
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
            
[2025-04-10T13:36:59.085+0000] {base.py:794} INFO - Stopping heartbeat thread
[2025-04-10T13:37:02.090+0000] {base.py:995} WARNING - Heartbeat thread did not fully terminate during close
[2025-04-10T13:37:02.091+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:37:02.093+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:37:02.094+0000] {python.py:237} INFO - Done. Returned value was: 1
[2025-04-10T13:37:02.094+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-10T13:37:02.153+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_v2, task_id=process_kafka_data, execution_date=20250410T000000, start_date=20250410T132953, end_date=20250410T133702
[2025-04-10T13:37:02.207+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-10T13:37:02.250+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-10T13:37:02.254+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
