[2025-04-10T13:18:50.201+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-10T13:18:50.224+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-10T13:18:50.232+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-10T13:18:50.233+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2025-04-10T13:18:50.246+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_kafka_data> on 2025-04-10 00:00:00+00:00
[2025-04-10T13:18:50.252+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-10T13:18:50.254+0000] {standard_task_runner.py:63} INFO - Started process 7671 to run task
[2025-04-10T13:18:50.254+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_v2', 'process_kafka_data', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '1020', '--raw', '--subdir', 'DAGS_FOLDER/dag_tmdb.py', '--cfg-path', '/tmp/tmpqayo_yzb']
[2025-04-10T13:18:50.257+0000] {standard_task_runner.py:91} INFO - Job 1020: Subtask process_kafka_data
[2025-04-10T13:18:50.305+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_v2.process_kafka_data scheduled__2025-04-10T00:00:00+00:00 [running]> on host a24902f77b45
[2025-04-10T13:18:50.409+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_v2' AIRFLOW_CTX_TASK_ID='process_kafka_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-10T13:18:50.410+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-10T13:18:50.531+0000] {dag_tmdb.py:283} INFO - Iniciando proceso de consumo de datos de Kafka
[2025-04-10T13:18:50.533+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T13:18:50.537+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <checking_api_versions_recv> [IPv4 ('172.19.0.6', 9093)]>: Broker version identified as 2.6
[2025-04-10T13:18:50.538+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T13:18:50.539+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('tmdb_data',)
[2025-04-10T13:18:50.540+0000] {dag_tmdb.py:295} INFO - Consumidor conectado a Kafka, esperando mensajes en 'tmdb_data'...
[2025-04-10T13:18:50.540+0000] {dag_tmdb.py:339} INFO - Intento 1/3 de obtener mensajes
[2025-04-10T13:18:50.543+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T13:18:50.543+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T13:18:50.544+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:18:50.648+0000] {cluster.py:393} INFO - Group coordinator for ***_consumer_group_v2 is ('coordinator-1001', 'kafka', 9093, None)
[2025-04-10T13:18:50.649+0000] {base.py:729} INFO - Discovered coordinator coordinator-1001 for group ***_consumer_group_v2
[2025-04-10T13:18:50.650+0000] {base.py:780} INFO - Starting new heartbeat thread
[2025-04-10T13:18:50.651+0000] {consumer.py:361} INFO - Revoking previously assigned partitions () for group ***_consumer_group_v2
[2025-04-10T13:18:50.652+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T13:18:50.653+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T13:18:50.754+0000] {base.py:489} INFO - (Re-)joining group ***_consumer_group_v2
[2025-04-10T13:18:50.760+0000] {base.py:552} INFO - Elected group leader -- performing partition assignments using range
[2025-04-10T13:18:50.764+0000] {base.py:380} INFO - Successfully joined group ***_consumer_group_v2 with generation 15
[2025-04-10T13:18:50.765+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('tmdb_data', 0)]
[2025-04-10T13:18:50.765+0000] {consumer.py:252} INFO - Setting newly assigned partitions (('tmdb_data', 0),) for group ***_consumer_group_v2
[2025-04-10T13:18:50.783+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Una noche en Zoopolis
[2025-04-10T13:18:50.784+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: El ejecutor
[2025-04-10T13:18:50.784+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Las Quintillizas: La Película
[2025-04-10T13:18:50.784+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: So Won
[2025-04-10T13:18:50.784+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Una película de Minecraft
[2025-04-10T13:18:50.785+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Henry Danger: La película
[2025-04-10T13:18:50.785+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Gabriel's Inferno
[2025-04-10T13:18:50.785+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Pídeme lo que quieras
[2025-04-10T13:18:50.786+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Gladiator II
[2025-04-10T13:18:50.786+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Apocalypse Now
[2025-04-10T13:18:50.786+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Ghost Game
[2025-04-10T13:18:50.786+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: El pianista
[2025-04-10T13:18:50.787+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Until Dawn
[2025-04-10T13:18:50.787+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Queer
[2025-04-10T13:18:50.787+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: El maestro del crimen
[2025-04-10T13:18:50.787+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: La lista de Schindler
[2025-04-10T13:18:50.788+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: El club de los poetas muertos
[2025-04-10T13:18:50.788+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Norma: Antara Mertua dan Menantu
[2025-04-10T13:18:50.788+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Vaiana 2
[2025-04-10T13:18:50.789+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: El imperio contraataca
[2025-04-10T13:18:50.789+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: El abismo secreto
[2025-04-10T13:18:50.789+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Mickey 17
[2025-04-10T13:18:50.789+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Red One
[2025-04-10T13:18:50.790+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Z Zone
[2025-04-10T13:18:50.790+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Cuando cae el otoño
[2025-04-10T13:18:50.790+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Los caballeros de la mesa cuadrada y sus locos seguidores
[2025-04-10T13:18:50.790+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: 365 días: Aquel día
[2025-04-10T13:18:50.791+0000] {dag_tmdb.py:346} INFO - Recibido mensaje: Fight or Flight
[2025-04-10T13:18:50.791+0000] {dag_tmdb.py:349} INFO - Recibidos 28 mensajes, procediendo a procesar
[2025-04-10T13:18:50.791+0000] {dag_tmdb.py:378} INFO - Procesando 28 mensajes con Pandas
[2025-04-10T13:18:50.799+0000] {dag_tmdb.py:439} ERROR - Error en el procesamiento: sequence item 0: expected str instance, dict found
[2025-04-10T13:18:50.803+0000] {dag_tmdb.py:440} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/dag_tmdb.py", line 401, in process_kafka_data
    df['cast_str'] = df['cast'].apply(lambda x: ','.join(x) if isinstance(x, list) else '')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/series.py", line 4764, in apply
    ).apply()
      ^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1209, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1289, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "/opt/***/dags/dag_tmdb.py", line 401, in <lambda>
    df['cast_str'] = df['cast'].apply(lambda x: ','.join(x) if isinstance(x, list) else '')
                                                ^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, dict found

[2025-04-10T13:18:50.806+0000] {base.py:794} INFO - Stopping heartbeat thread
[2025-04-10T13:18:53.808+0000] {base.py:995} WARNING - Heartbeat thread did not fully terminate during close
[2025-04-10T13:18:53.809+0000] {base.py:823} INFO - Leaving consumer group (***_consumer_group_v2).
[2025-04-10T13:18:53.813+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:18:53.814+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=coordinator-1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:18:53.817+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-10T13:18:53.817+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_tmdb.py", line 401, in process_kafka_data
    df['cast_str'] = df['cast'].apply(lambda x: ','.join(x) if isinstance(x, list) else '')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 4764, in apply
    ).apply()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1209, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1289, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/dag_tmdb.py", line 401, in <lambda>
    df['cast_str'] = df['cast'].apply(lambda x: ','.join(x) if isinstance(x, list) else '')
                                                ^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, dict found
[2025-04-10T13:18:53.828+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tmdb_pipeline_v2, task_id=process_kafka_data, execution_date=20250410T000000, start_date=20250410T131850, end_date=20250410T131853
[2025-04-10T13:18:53.840+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1020 for task process_kafka_data (sequence item 0: expected str instance, dict found; 7671)
[2025-04-10T13:18:53.877+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-10T13:18:53.901+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T13:18:53.902+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
