[2025-04-05T15:22:42.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T15:22:42.098+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_advanced.setup_environment scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-05T15:22:42.105+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_advanced.setup_environment scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-05T15:22:42.105+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-05T15:22:42.118+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): setup_environment> on 2025-04-05 00:00:00+00:00
[2025-04-05T15:22:42.127+0000] {standard_task_runner.py:63} INFO - Started process 258 to run task
[2025-04-05T15:22:42.130+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_advanced', 'setup_environment', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmp4xbxjgdz']
[2025-04-05T15:22:42.133+0000] {standard_task_runner.py:91} INFO - Job 289: Subtask setup_environment
[2025-04-05T15:22:42.182+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_advanced.setup_environment scheduled__2025-04-05T00:00:00+00:00 [running]> on host 11624d9102e2
[2025-04-05T15:22:42.279+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_advanced' AIRFLOW_CTX_TASK_ID='setup_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-05T15:22:42.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T15:22:42.312+0000] {tmdb_pipeline.py:1594} INFO - Preparando entorno para el pipeline TMDB...
[2025-04-05T15:22:42.312+0000] {tmdb_pipeline.py:1598} INFO - Directorio de salida creado: /opt/***/data/movie_analytics
[2025-04-05T15:22:42.314+0000] {tmdb_pipeline.py:1690} ERROR - Error al crear tablas en PostgreSQL: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-05T15:22:42.318+0000] {tmdb_pipeline.py:1691} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 1603, in setup_environment
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.4), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-05T15:22:42.318+0000] {tmdb_pipeline.py:1697} WARNING - Hubo problemas preparando el entorno, pero continuaremos
[2025-04-05T15:22:42.319+0000] {python.py:237} INFO - Done. Returned value was: setup_completed
[2025-04-05T15:22:42.319+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T15:22:42.345+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_advanced, task_id=setup_environment, execution_date=20250405T000000, start_date=20250405T152242, end_date=20250405T152242
[2025-04-05T15:22:42.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T15:22:42.420+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T15:22:42.421+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
