[2025-04-07T21:34:46.845+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T21:34:46.870+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.verify_model_availability manual__2025-04-07T21:26:08.066209+00:00 [queued]>
[2025-04-07T21:34:46.879+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.verify_model_availability manual__2025-04-07T21:26:08.066209+00:00 [queued]>
[2025-04-07T21:34:46.880+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-04-07T21:34:46.895+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): verify_model_availability> on 2025-04-07 21:26:08.066209+00:00
[2025-04-07T21:34:46.905+0000] {standard_task_runner.py:63} INFO - Started process 549 to run task
[2025-04-07T21:34:46.908+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'verify_model_availability', 'manual__2025-04-07T21:26:08.066209+00:00', '--job-id', '611', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmpvjggpofs']
[2025-04-07T21:34:46.911+0000] {standard_task_runner.py:91} INFO - Job 611: Subtask verify_model_availability
[2025-04-07T21:34:46.962+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.verify_model_availability manual__2025-04-07T21:26:08.066209+00:00 [running]> on host 7a9fb61be003
[2025-04-07T21:34:47.058+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='verify_model_availability' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T21:26:08.066209+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T21:26:08.066209+00:00'
[2025-04-07T21:34:47.059+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T21:34:47.073+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T21:34:47.073+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tmdb_pipeline.py", line 2907, in <lambda>
    python_callable=lambda **kwargs: print(f"Verificando que el modelo est√© disponible en: {ML_MODELS_DIR}"),
                                                                                            ^^^^^^^^^^^^^
NameError: name 'ML_MODELS_DIR' is not defined
[2025-04-07T21:34:47.090+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=tmdb_pipeline_streamlit, task_id=verify_model_availability, execution_date=20250407T212608, start_date=20250407T213446, end_date=20250407T213447
[2025-04-07T21:34:47.102+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 611 for task verify_model_availability (name 'ML_MODELS_DIR' is not defined; 549)
[2025-04-07T21:34:47.131+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-07T21:34:47.156+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T21:34:47.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
