[2025-04-07T02:54:07.986+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T02:54:08.009+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.load_to_postgres manual__2025-04-07T02:53:36.443360+00:00 [queued]>
[2025-04-07T02:54:08.017+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.load_to_postgres manual__2025-04-07T02:53:36.443360+00:00 [queued]>
[2025-04-07T02:54:08.018+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-07T02:54:08.030+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-07 02:53:36.443360+00:00
[2025-04-07T02:54:08.036+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T02:54:08.038+0000] {standard_task_runner.py:63} INFO - Started process 261 to run task
[2025-04-07T02:54:08.038+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'load_to_postgres', 'manual__2025-04-07T02:53:36.443360+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmps0wq_m8p']
[2025-04-07T02:54:08.040+0000] {standard_task_runner.py:91} INFO - Job 401: Subtask load_to_postgres
[2025-04-07T02:54:08.085+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.load_to_postgres manual__2025-04-07T02:53:36.443360+00:00 [running]> on host e27f0cb72674
[2025-04-07T02:54:08.173+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T02:53:36.443360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T02:53:36.443360+00:00'
[2025-04-07T02:54:08.174+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T02:54:08.211+0000] {tmdb_pipeline.py:1477} INFO - Leyendo 10 registros procesados para cargar en PostgreSQL
[2025-04-07T02:54:08.212+0000] {tmdb_pipeline.py:1106} ERROR - Error al crear tablas en PostgreSQL: connection to server at "movie_postgres" (172.19.0.5), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-07T02:54:08.214+0000] {tmdb_pipeline.py:1107} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 999, in create_postgres_tables
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.5), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-07T02:54:08.215+0000] {tmdb_pipeline.py:1656} ERROR - Error al conectar o insertar en PostgreSQL: connection to server at "movie_postgres" (172.19.0.5), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-07T02:54:08.216+0000] {tmdb_pipeline.py:1657} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/tmdb_pipeline.py", line 1484, in load_to_postgres
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/***/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "movie_postgres" (172.19.0.5), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


[2025-04-07T02:54:08.216+0000] {tmdb_pipeline.py:1660} INFO - Intentando m√©todo alternativo: guardar resultados como CSV
[2025-04-07T02:54:08.222+0000] {tmdb_pipeline.py:1665} INFO - Resultados guardados en /opt/***/data/movie_analytics/results_data_v3.csv
[2025-04-07T02:54:08.223+0000] {python.py:237} INFO - Done. Returned value was: 0
[2025-04-07T02:54:08.223+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T02:54:08.243+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_streamlit, task_id=load_to_postgres, execution_date=20250407T025336, start_date=20250407T025408, end_date=20250407T025408
[2025-04-07T02:54:08.260+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-07T02:54:08.287+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-07T02:54:08.289+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
