[2025-04-10T12:14:02.774+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-10T12:14:02.795+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.fetch_and_send_to_kafka scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-10T12:14:02.803+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline_streamlit.fetch_and_send_to_kafka scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-10T12:14:02.804+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-04-10T12:14:02.843+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_and_send_to_kafka> on 2025-04-10 00:00:00+00:00
[2025-04-10T12:14:02.854+0000] {standard_task_runner.py:63} INFO - Started process 7626 to run task
[2025-04-10T12:14:02.857+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline_streamlit', 'fetch_and_send_to_kafka', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '1017', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmpnf_lhydz']
[2025-04-10T12:14:02.860+0000] {standard_task_runner.py:91} INFO - Job 1017: Subtask fetch_and_send_to_kafka
[2025-04-10T12:14:02.910+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline_streamlit.fetch_and_send_to_kafka scheduled__2025-04-10T00:00:00+00:00 [running]> on host a24902f77b45
[2025-04-10T12:14:03.001+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tmdb_pipeline_streamlit' AIRFLOW_CTX_TASK_ID='fetch_and_send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-10T12:14:03.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-10T12:14:03.114+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T12:14:03.118+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9093 <checking_api_versions_recv> [IPv4 ('172.19.0.6', 9093)]>: Broker version identified as 2.6
[2025-04-10T12:14:03.119+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T12:14:03.120+0000] {tmdb_pipeline.py:448} INFO - Productor Kafka conectado a kafka:9093
[2025-04-10T12:14:03.121+0000] {tmdb_pipeline.py:461} INFO - Obteniendo películas populares de TMDB
[2025-04-10T12:14:03.360+0000] {tmdb_pipeline.py:468} INFO - Obtenidas 20 películas populares (página 1)
[2025-04-10T12:14:03.644+0000] {tmdb_pipeline.py:468} INFO - Obtenidas 20 películas populares (página 2)
[2025-04-10T12:14:03.921+0000] {tmdb_pipeline.py:468} INFO - Obtenidas 20 películas populares (página 3)
[2025-04-10T12:14:04.254+0000] {tmdb_pipeline.py:468} INFO - Obtenidas 20 películas populares (página 4)
[2025-04-10T12:14:04.530+0000] {tmdb_pipeline.py:468} INFO - Obtenidas 20 películas populares (página 5)
[2025-04-10T12:14:04.531+0000] {tmdb_pipeline.py:477} INFO - Obteniendo películas mejor valoradas de TMDB
[2025-04-10T12:14:04.813+0000] {tmdb_pipeline.py:484} INFO - Obtenidas 20 películas mejor valoradas (página 1)
[2025-04-10T12:14:05.090+0000] {tmdb_pipeline.py:484} INFO - Obtenidas 20 películas mejor valoradas (página 2)
[2025-04-10T12:14:05.361+0000] {tmdb_pipeline.py:484} INFO - Obtenidas 20 películas mejor valoradas (página 3)
[2025-04-10T12:14:05.632+0000] {tmdb_pipeline.py:484} INFO - Obtenidas 20 películas mejor valoradas (página 4)
[2025-04-10T12:14:05.943+0000] {tmdb_pipeline.py:484} INFO - Obtenidas 20 películas mejor valoradas (página 5)
[2025-04-10T12:14:05.943+0000] {tmdb_pipeline.py:493} INFO - Obteniendo próximos estrenos de TMDB
[2025-04-10T12:14:06.244+0000] {tmdb_pipeline.py:500} INFO - Obtenidos 20 próximos estrenos (página 1)
[2025-04-10T12:14:06.514+0000] {tmdb_pipeline.py:500} INFO - Obtenidos 20 próximos estrenos (página 2)
[2025-04-10T12:14:06.857+0000] {tmdb_pipeline.py:500} INFO - Obtenidos 20 próximos estrenos (página 3)
[2025-04-10T12:14:06.857+0000] {tmdb_pipeline.py:510} INFO - Total de 238 IDs de películas únicas recolectadas
[2025-04-10T12:14:06.859+0000] {tmdb_pipeline.py:516} INFO - IDs de películas guardados en /opt/***/data/movie_analytics/movie_ids_20250410.json
[2025-04-10T12:14:06.860+0000] {tmdb_pipeline.py:526} INFO - Obteniendo detalles de 100 películas
[2025-04-10T12:14:07.138+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T12:14:07.139+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T12:14:07.140+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T12:14:07.146+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Anora
[2025-04-10T12:14:07.931+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: A Silent Voice
[2025-04-10T12:14:08.735+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Deadpool y Lobezno
[2025-04-10T12:14:09.519+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: El despertar de la bestia
[2025-04-10T12:14:10.339+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Toda una vida en un año
[2025-04-10T12:14:11.124+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Uno de los nuestros
[2025-04-10T12:14:11.907+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Del revés 2 (Inside Out 2)
[2025-04-10T12:14:12.682+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: La leyenda del pianista en el océano
[2025-04-10T12:14:13.454+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Amenaza en el aire
[2025-04-10T12:14:14.291+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Escape
[2025-04-10T12:14:15.061+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Un ángel en nuestras vidas
[2025-04-10T12:14:15.850+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Una noche en Zoopolis
[2025-04-10T13:14:59.719+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1197306: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1197306?append_to_response=credits&language=es-ES (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2025-04-10T13:15:00.295+0000] {client_async.py:1147} INFO - Closing idle connection 1001, last active 3644445 ms ago
[2025-04-10T13:15:00.296+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:15:00.300+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1001 host=kafka:9093 <connecting> [IPv4 ('172.19.0.6', 9093)]>: connecting to kafka:9093 [('172.19.0.6', 9093) IPv4]
[2025-04-10T13:15:00.301+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Connection complete.
[2025-04-10T13:15:00.311+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: El ejecutor
[2025-04-10T13:15:01.378+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Las Quintillizas: La Película
[2025-04-10T13:15:02.195+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: So Won
[2025-04-10T13:15:02.984+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Una película de Minecraft
[2025-04-10T13:15:03.843+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Henry Danger: La película
[2025-04-10T13:15:04.629+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Gabriel's Inferno
[2025-04-10T13:15:05.469+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Pídeme lo que quieras
[2025-04-10T13:15:06.281+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Gladiator II
[2025-04-10T13:15:07.089+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Apocalypse Now
[2025-04-10T13:15:07.873+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Ghost Game
[2025-04-10T13:15:08.658+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: El pianista
[2025-04-10T13:15:09.430+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Until Dawn
[2025-04-10T13:15:10.241+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Queer
[2025-04-10T13:15:11.041+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: El maestro del crimen
[2025-04-10T13:15:11.841+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: La lista de Schindler
[2025-04-10T13:15:12.636+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: El club de los poetas muertos
[2025-04-10T13:15:13.449+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Norma: Antara Mertua dan Menantu
[2025-04-10T13:15:14.243+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Vaiana 2
[2025-04-10T13:15:15.022+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: El imperio contraataca
[2025-04-10T13:15:15.860+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: El abismo secreto
[2025-04-10T13:15:16.868+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Mickey 17
[2025-04-10T13:15:17.812+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Red One
[2025-04-10T13:15:19.251+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Z Zone
[2025-04-10T13:15:20.252+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Cuando cae el otoño
[2025-04-10T13:15:21.042+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Los caballeros de la mesa cuadrada y sus locos seguidores
[2025-04-10T13:15:21.833+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: 365 días: Aquel día
[2025-04-10T13:15:22.604+0000] {tmdb_pipeline.py:583} INFO - Película enviada a Kafka: Fight or Flight
[2025-04-10T13:15:31.181+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 569094: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/569094?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.283+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 324857: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/324857?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8d10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.355+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 632632: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/632632?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.408+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1275248: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1275248?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e82c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.463+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 912649: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/912649?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8eacc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.543+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 321883: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/321883?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8eb1d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.570+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 761053: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/761053?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ea5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.611+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 4232: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/4232?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8eaf60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.720+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 724089: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/724089?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8a40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.805+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1265623: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1265623?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8530>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.839+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 490132: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/490132?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8eaba0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.864+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 278: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/278?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.887+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1254786: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1254786?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a6e7c3fb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.917+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1249289: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1249289?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8b00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:31.977+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1156593: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1156593?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.027+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 823219: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/823219?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8e00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.067+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 986056: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/986056?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.102+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 807: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/807?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8e00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.113+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1373723: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1373723?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e94f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.126+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1018: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1018?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8e00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.138+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 668489: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/668489?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e94f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.157+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 978592: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/978592?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8e00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.168+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 652837: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/652837?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e94f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.184+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 18491: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/18491?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ea6c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.200+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 105: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/105?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8afad0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.211+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1269941: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1269941?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.221+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 389: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/389?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8830>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.233+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 77338: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/77338?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8830>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.262+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1010581: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1010581?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ebb60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.273+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 324544: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/324544?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9010>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.283+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1441734: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1441734?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ea6f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.296+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 283566: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/283566?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ea6f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.306+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 4348: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/4348?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8eac00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.321+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1064486: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1064486?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8eac00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.349+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 667257: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/667257?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ebe00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.359+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 972533: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/972533?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9160>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.368+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 516729: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/516729?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ea4b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.378+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1261050: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1261050?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a3c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.387+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 447273: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/447273?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8ea6f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.394+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 155: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/155?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d718410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.403+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1140535: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1140535?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a7b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.411+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 25237: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/25237?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e8e00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.432+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 120: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/120?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8eac00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.456+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 680: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/680?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d719280>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.463+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 73: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/73?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d7186b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.476+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 157336: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/157336?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a4b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.488+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 637920: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/637920?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.495+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1233413: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1233413?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a4b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.503+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1124620: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1124620?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71b680>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.519+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1109255: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1109255?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a360>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.530+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 901: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/901?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a4b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.551+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1895: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1895?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.564+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1103621: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1103621?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.574+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 129: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/129?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a6f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.586+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1333099: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1333099?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d718410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.596+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 250546: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/250546?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d71a6f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.604+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1139087: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1139087?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.613+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1153714: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1153714?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a6e7c0c80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.623+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 670: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/670?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d8e9790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.632+0000] {tmdb_pipeline.py:597} ERROR - Error procesando película ID 1241436: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/movie/1241436?append_to_response=credits&language=es-ES (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5d7198b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-04-10T13:15:32.642+0000] {kafka.py:511} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-04-10T13:15:32.704+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1001 host=kafka:9093 <connected> [IPv4 ('172.19.0.6', 9093)]>: Closing connection. 
[2025-04-10T13:15:32.714+0000] {tmdb_pipeline.py:610} INFO - Proceso completado. 39 películas procesadas.
[2025-04-10T13:15:32.940+0000] {python.py:237} INFO - Done. Returned value was: 39
[2025-04-10T13:15:32.948+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-10T13:15:33.011+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline_streamlit, task_id=fetch_and_send_to_kafka, execution_date=20250410T000000, start_date=20250410T121402, end_date=20250410T131533
[2025-04-10T13:15:33.171+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-10T13:15:33.283+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-10T13:15:33.287+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
