[2025-04-01T18:38:01.506+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-01T18:38:01.528+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline.process_kafka_data scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-01T18:38:01.536+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline.process_kafka_data scheduled__2025-04-01T00:00:00+00:00 [queued]>
[2025-04-01T18:38:01.536+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-01T18:38:01.549+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_kafka_data> on 2025-04-01 00:00:00+00:00
[2025-04-01T18:38:01.554+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-01T18:38:01.556+0000] {standard_task_runner.py:63} INFO - Started process 100 to run task
[2025-04-01T18:38:01.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline', 'process_kafka_data', 'scheduled__2025-04-01T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmpeqflbzcj']
[2025-04-01T18:38:01.559+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask process_kafka_data
[2025-04-01T18:38:01.604+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline.process_kafka_data scheduled__2025-04-01T00:00:00+00:00 [running]> on host 488700525f48
[2025-04-01T18:38:01.685+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline' AIRFLOW_CTX_TASK_ID='process_kafka_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-01T00:00:00+00:00'
[2025-04-01T18:38:01.686+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-01T18:38:04.011+0000] {proxy.py:85} INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
[2025-04-01T18:38:04.068+0000] {scheduler.py:1754} INFO - State start
[2025-04-01T18:38:04.073+0000] {diskutils.py:252} INFO - Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-pnvwvfgq', purging
[2025-04-01T18:38:04.075+0000] {diskutils.py:252} INFO - Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-fecstmm3', purging
[2025-04-01T18:38:04.088+0000] {scheduler.py:4209} INFO -   Scheduler at:     tcp://127.0.0.1:33631
[2025-04-01T18:38:04.090+0000] {scheduler.py:4224} INFO -   dashboard at:  http://127.0.0.1:8787/status
[2025-04-01T18:38:04.091+0000] {scheduler.py:8127} INFO - Registering Worker plugin shuffle
[2025-04-01T18:38:04.114+0000] {nanny.py:368} INFO -         Start Nanny at: 'tcp://127.0.0.1:44809'
[2025-04-01T18:38:04.128+0000] {nanny.py:368} INFO -         Start Nanny at: 'tcp://127.0.0.1:33909'
[2025-04-01T18:38:04.134+0000] {nanny.py:454} ERROR - Failed to start process
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/nanny.py", line 452, in instantiate
    result = await self.process.start()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/nanny.py", line 750, in start
    await self.process.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/process.py", line 55, in _call_and_set_future
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/process.py", line 215, in _start
    process.start()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
[2025-04-01T18:38:04.140+0000] {nanny.py:611} INFO - Closing Nanny at 'tcp://127.0.0.1:44809'. Reason: nanny-instantiate-failed
[2025-04-01T18:38:04.141+0000] {nanny.py:454} ERROR - Failed to start process
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/nanny.py", line 452, in instantiate
    result = await self.process.start()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/nanny.py", line 750, in start
    await self.process.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/process.py", line 55, in _call_and_set_future
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/distributed/process.py", line 215, in _start
    process.start()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
[2025-04-01T18:38:04.142+0000] {nanny.py:611} INFO - Closing Nanny at 'tcp://127.0.0.1:33909'. Reason: nanny-instantiate-failed
