[2025-04-04T00:32:46.939+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-04T00:32:47.093+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tmdb_pipeline.train_ml_model scheduled__2025-04-03T12:00:00+00:00 [queued]>
[2025-04-04T00:32:47.175+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tmdb_pipeline.train_ml_model scheduled__2025-04-03T12:00:00+00:00 [queued]>
[2025-04-04T00:32:47.178+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-04-04T00:32:47.298+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train_ml_model> on 2025-04-03 12:00:00+00:00
[2025-04-04T00:32:47.347+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2373) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-04T00:32:47.359+0000] {standard_task_runner.py:63} INFO - Started process 2375 to run task
[2025-04-04T00:32:47.360+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tmdb_pipeline', 'train_ml_model', 'scheduled__2025-04-03T12:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_pipeline.py', '--cfg-path', '/tmp/tmpx2eimvn5']
[2025-04-04T00:32:47.382+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask train_ml_model
[2025-04-04T00:32:47.661+0000] {task_command.py:426} INFO - Running <TaskInstance: tmdb_pipeline.train_ml_model scheduled__2025-04-03T12:00:00+00:00 [running]> on host 29a2839b1f8c
[2025-04-04T00:32:48.271+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriela' AIRFLOW_CTX_DAG_ID='tmdb_pipeline' AIRFLOW_CTX_TASK_ID='train_ml_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-03T12:00:00+00:00'
[2025-04-04T00:32:48.278+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-04T00:32:58.955+0000] {tmdb_pipeline.py:666} ERROR - Error al leer datos de PostgreSQL para ML: connection to server at "movie_postgres" (172.19.0.3), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-04T00:33:02.028+0000] {tmdb_pipeline.py:740} INFO - Modelo ML entrenado y guardado en /opt/***/data/movie_analytics/ml_model_20250404_003259
[2025-04-04T00:33:02.031+0000] {tmdb_pipeline.py:741} INFO - Métricas del modelo - MSE: 13005.3755, R²: -0.1924
[2025-04-04T00:33:02.209+0000] {python.py:237} INFO - Done. Returned value was: /opt/***/data/movie_analytics/ml_model_20250404_003259
[2025-04-04T00:33:02.216+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-04T00:33:02.349+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tmdb_pipeline, task_id=train_ml_model, execution_date=20250403T120000, start_date=20250404T003247, end_date=20250404T003302
[2025-04-04T00:33:02.667+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-04T00:33:02.837+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-04T00:33:02.845+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
